### ISSUE TITLE
TypeError: Cannot set property 'font' of null

### ISSUE THREAD

**Issue by xiakehc** [mikolalysenko/vectorize-text#7]
![image](https://user-images.githubusercontent.com/3898789/35547523-75f1fba8-05b4-11e8-9a91-6ca8d6249b46.png)

**Comment by xiakehc** [comment]
how to solve?

**Comment by atkinchris** [comment]
Are you using [`node-canvas`](https://github.com/Automattic/node-canvas#installation), with Cairo installed, and passing the `canvas` and `context` in the options?

**Comment by hktalent** [comment]
me too
```
"font":'FZSong-RKXX'

TypeError: Cannot set property 'font' of null
    at vectorizeText (/usr/local/lib/node_modules/vectorize-text/lib/vtext.js:196:16)
    at createText (/usr/local/lib/node_modules/vectorize-text/index.js:20:10)
    at fnT2Svg (/Users/xiatian/safe/myhktools/txt2SVG.js:5:17)

```

**Comment by atkinchris** [comment]
@hktalent - as per my comment above, are you using [`node-canvas`](https://github.com/Automattic/node-canvas#installation), and passing the canvas and it's context 
 as `canvas` and `context` respectively in the options object?

```js
const { createCanvas } = require('canvas')
const vectorizeText = require('vectorize-text')

const width = 200
const height = 200
const canvas = createCanvas(width, height)
const context = canvas.getContext('2d')

vectorizeText('Hello world', {
  font: 'Sans-serif',
  width,
  canvas,
  context,
})
```

**Comment by GuiRitter** [comment]
I adapted the example provided in [the read me](https://github.com/mikolalysenko/vectorize-text/blob/master/README.md) with [the comment above](https://github.com/mikolalysenko/vectorize-text/issues/7#issuecomment-371524288) and this is what I'm seeing:

![vectorize-text-test](https://svgshare.com/i/7jz.svg)

> example.js

```javascript
const { createCanvas } = require('canvas')
var vectorizeText = require("vectorize-text")

const width = 500
const height = 80
const canvas = createCanvas(width, height)
const context = canvas.getContext('2d')

var graph = vectorizeText("Hello world! 你好", {
  //width: 500,
  textBaseline: "hanging",
  font: 'Sans-serif',
  width,
  canvas,
  context,
})

var svg = ['<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"  width="500"  height="80" >']
graph.edges.forEach(function(e) {
  var p0 = graph.positions[e[0]]
  var p1 = graph.positions[e[1]]
  svg.push('<line x1="' + p0[0] + '" y1="' + p0[1] +
    '" x2="' + p1[0] + '" y2="' + p1[1] +
    '" stroke-width="1" stroke="black" />')
})
svg.push("</svg>")

console.log(svg.join(""))
```

**EDIT:** for those looking for a solution, I reccomend [text-to-svg](https://github.com/shrhdk/text-to-svg) instead.
